from novelinsights.types.base import DescribedEnum

class CreationSourceType(DescribedEnum):
    """Source of content in the system"""
    HUMAN = ("human", "Content written by human authors")
    AI = ("ai", "Content generated by AI")
