# generated by datamodel-codegen:
#   filename:  core_summary_schema.json
#   timestamp: 2024-10-15T01:01:30+00:00

from __future__ import annotations

from enum import Enum
from typing import List
import jsonref

from pydantic import BaseModel, Field


class Status(Enum):
    ongoing = 'ongoing'
    complete = 'complete'


class PlotOverviewItem(BaseModel):
    arc_name: str = Field(..., description='A concise name or title for the arc')
    description: str = Field(
        ...,
        description="A summary of the arc's storyline, including main events and primary conflicts",
    )
    status: Status = Field(..., description='The current status of the arc')


class CoreSummaryModel(BaseModel):
    class Config:
        extra = 'forbid'

    genres: List[str]
    setting: str = Field(
        ...,
        description='Description of the primary setting or world in which the story takes place',
    )
    overall_summary: str = Field(
        ...,
        description='A detailed summary of the entire story so far, highlighting the main plot developments. For longer descriptions, use markdown with headers and subheaders to organize.',
    )
    plot_overview: List[PlotOverviewItem] = Field(
        ..., description='A list of key arcs spanning multiple chapters'
    )
    
    def to_json_schema():
        ret = jsonref.replace_refs(super(CoreSummaryModel,CoreSummaryModel).model_json_schema(), proxies=False)
        del ret['$defs']
        return ret