# generated by datamodel-codegen:
#   filename:  location_schema.json
#   timestamp: 2024-10-15T01:41:26+00:00

from __future__ import annotations

from typing import List, Optional
import jsonref

from pydantic import BaseModel, Field

class KeyFeature(BaseModel):
    name: str = Field(..., description='Name of the key feature')
    description: str = Field(
        ..., description='Detailed description of the feature and its significance'
    )

class NearbyItem(BaseModel):
    name: str = Field(..., description='Name of the nearby location')
    distance: str = Field(
        ..., description='Approximate distance and direction from the main location'
    )
    connection: Optional[str] = Field(
        None,
        description='Brief description of the relationship or relevance to the main location',
    )

class LocationModel(BaseModel):
    class Config:
        extra = 'forbid'

    name: str = Field(..., description='The primary name of the location')
    aliases: Optional[List[str]] = Field(
        None, description='Alternative names or designations for the location'
    )
    overview: str = Field(
        ...,
        description='A concise summary of the location, including its type (e.g., city, country, planet), basic characteristics, and general significance',
    )
    significance: str = Field(
        ...,
        description="The location's importance to the plot and how it impacts the story",
    )
    setting: Optional[str] = Field(
        None,
        description="Comprehensive description of the location's setting, including physical characteristics like layout, terrain, climate, and notable features and for cities, this can include urban planning, architecture, and districts. Also include descriptions about the society like the location's inhabitants, governance, culture, and economy. For longer descriptions, use markdown with headers and subheaders to organize.",
    )
    key_features: Optional[List[KeyFeature]] = Field(
        None, description='List of notable or unique features of the location'
    )
    background: str = Field(
        ...,
        description='Detailed history and lore of the location. For longer descriptions, use markdown with headers and subheaders to organize.',
    )
    nearby: Optional[List[NearbyItem]] = Field(
        None,
        description='List of nearby locations and their connections to the main location',
    )
    
    def to_json_schema():
        ret = jsonref.replace_refs(super().model_json_schema(), proxies=False)
        del ret['$defs']
        return ret